services:
  mc:
    image: itzg/minecraft-server
    environment:
      EULA: "TRUE"
      ONLINE_MODE: "FALSE"
  proxy:
    image: itzg/bungeecord
    environment:
      TYPE: VELOCITY
      DEBUG: "false"
      ENABLE_RCON: "true"
    ports:
      - "25565:25577"
    volumes:
      - ./velocity.toml:/server/velocity.toml
      - proxy:/server

volumes:
  proxy: {}
