services:
  mc:
    image: itzg/minecraft-server
    environment:
      EULA: "TRUE"
      ONLINE_MODE: "FALSE"
      TYPE: PAPER
  proxy:
    image: itzg/bungeecord
    environment:
      TYPE: VELOCITY
      DEBUG: "false"
      ENABLE_RCON: "true"
    ports:
      - "25565:25577"
    volumes:
      - ./velocity.toml:/config/velocity.toml:ro
      - ./forwarding.secret:/config/forwarding.secret:ro
      - proxy:/server

volumes:
  proxy: {}
