version: '3.5'

services:
  mc:
    image: itzg/minecraft-server
    environment:
      EULA: "TRUE"
      ONLINE_MODE: "FALSE"
  bungeecord:
    image: itzg/bungeecord
    environment:
      TYPE: WATERFALL
      ENABLE_RCON: "true"
      DEBUG: "false"
    ports:
      - 25565:25577
    volumes:
      - ./config.yml:/config/config.yml
