services:
  mc:
    image: itzg/minecraft-server
    environment:
      EULA: "TRUE"
      TYPE: PAPER
      ONLINE_MODE: "FALSE"
  proxy:
    image: itzg/bungeecord
    environment:
      TYPE: WATERFALL
      ENABLE_RCON: "true"
      DEBUG: "false"
    ports:
      - "25565:25577"
    volumes:
      - ./config.yml:/config/config.yml
